abbr dnfl "dnf5 list"
abbr dnfli "dnf5 list --installed"
abbr dnfmc "dnf5 makecache"
abbr dnfp "dnf5 info"
abbr dnfs "dnf5 search"
abbr dnfrq "dnf5 repoquery"

abbr dnfu "sudo dnf5 upgrade"
abbr dnfi "sudo dnf5 install"
abbr dnfri "sudo dnf5 reinstall"
abbr dnfsw "sudo dnf5 swap"
abbr dnfr "sudo dnf5 remove"
abbr dnfc "sudo dnf5 clean all"
